name: gql_build
version: 0.1.4+2
description: Useful builders for your GraphQL SDL and documents. Based on package:gql_code_builder and package:build
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.7.2 <3.0.0'
dependencies:
  analyzer: ^1.3.0
  build: ^2.0.0
  built_collection: ^5.0.0
  built_value: ^8.0.4
  built_value_generator: ^8.0.4
  code_builder: ^3.3.0
  dart_style: ^2.0.0
  glob: ^2.0.1
  gql: ^0.13.0-nullsafety.2
  gql_code_builder: ^0.2.0-nullsafety.0
  path: ^1.6.4
  yaml: ^3.1.0
dev_dependencies: 
  build_test: ^2.0.0
  gql_pedantic: ^1.0.2
